(()=>{
'use strict';
const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
const PRODUCTS=window.SANAAM_PRODUCTS||[],FAMILIES=window.SANAAM_FAMILIES||[],I18N=window.SANAAM_I18N||{},CONFIG=window.SANAAM_CONFIG||{};
const state={lang:localStorage.getItem('sanaam.lang')||'so'};
if(!I18N[state.lang])state.lang='so';
const t=(path)=>path.split('.').reduce((o,k)=>o?.[k],I18N[state.lang])??path;
const esc=(v)=>String(v??'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[c]||c));
const familyTitle=(id)=>{const f=FAMILIES.find(x=>x.id===id);return f?t(f.titleKey):id};
function renderProducts(){const featured=PRODUCTS.filter(p=>p.featured).slice(0,9);$('#featuredProducts').innerHTML=featured.map(p=>`<article class="product-card"><img src="${p.image}" alt="${esc(p.name)}" loading="lazy"><div class="product-content"><div class="grade">${esc(p.grade)}</div><h3>${esc(p.name)}</h3><p>${esc(p.type)}</p><div class="product-meta"><span>${esc(p.api)}</span><span>${esc(familyTitle(p.family))}</span></div><div class="pack-chips">${p.packaging.map(x=>`<i>${esc(x)}</i>`).join('')}</div></div></article>`).join('');$('#familyGrid').innerHTML=FAMILIES.map(f=>{const items=PRODUCTS.filter(p=>p.family===f.id);return `<article class="family-card"><strong>${esc(familyTitle(f.id))}</strong><p>${items.map(x=>esc(x.grade)).join(' · ')}</p></article>`}).join('');$('#fullRange').innerHTML=FAMILIES.map(f=>`<section class="family-range"><h3>${esc(familyTitle(f.id))}</h3><div class="range-chips">${PRODUCTS.filter(p=>p.family===f.id).map(p=>`<button type="button" data-rfq-product="${esc(p.id)}">${esc(p.grade)}</button>`).join('')}</div></section>`).join('');$$('[data-rfq-product]').forEach(btn=>btn.addEventListener('click',()=>{const sel=$('#rfqProduct');sel.value=btn.dataset.rfqProduct;syncPackOptions();$('#rfq').scrollIntoView({behavior:'smooth'})}))}
function renderApplications(){const cards=t('applications.cards');if(!Array.isArray(cards))return;$('#applicationsGrid').innerHTML=cards.map(c=>`<article class="application-card"><span>${esc(c.code)}</span><h3>${esc(c.title)}</h3><p>${esc(c.text)}</p><ul>${c.items.map(x=>`<li>${esc(x)}</li>`).join('')}</ul></article>`).join('')}
function renderProcesses(){const p=t('manufacturing.process');if(Array.isArray(p))$('#processList').innerHTML=p.map(x=>`<span>${esc(x)}</span>`).join('')}
function renderDistributorPoints(){const p=t('distributors.points');if(Array.isArray(p))$('#distributorPoints').innerHTML=p.map(x=>`<div>${esc(x)}</div>`).join('')}
function applyLanguage(){const lang=I18N[state.lang];document.documentElement.lang=state.lang;document.documentElement.dir=lang.dir;$$('[data-i18n]').forEach(el=>{const v=t(el.dataset.i18n);if(typeof v==='string')el.textContent=v});$$('[data-lang]').forEach(b=>b.classList.toggle('active',b.dataset.lang===state.lang));renderProducts();renderApplications();renderProcesses();renderDistributorPoints();populateRfqProducts(true)}
function populateRfqProducts(keep){const select=$('#rfqProduct');if(!select)return;const old=keep?select.value:'';select.innerHTML=PRODUCTS.map(p=>`<option value="${esc(p.id)}">${esc(p.name)} · ${esc(p.grade)}</option>`).join('');if(old&&PRODUCTS.some(p=>p.id===old))select.value=old;syncPackOptions()}
function syncPackOptions(){const p=PRODUCTS.find(x=>x.id===$('#rfqProduct')?.value)||PRODUCTS[0];const s=$('#rfqPack');if(!p||!s)return;const old=s.value;s.innerHTML=p.packaging.map(v=>`<option value="${esc(v)}">${esc(v)}</option>`).join('');if(p.packaging.includes(old))s.value=old}
function bindNavigation(){$$('[data-lang]').forEach(b=>b.addEventListener('click',()=>{state.lang=b.dataset.lang;localStorage.setItem('sanaam.lang',state.lang);applyLanguage()}));$('#menuToggle')?.addEventListener('click',()=>{const n=$('#mobileNav');n.classList.toggle('open');$('#menuToggle').setAttribute('aria-expanded',n.classList.contains('open'))});$$('#mobileNav a').forEach(a=>a.addEventListener('click',()=>$('#mobileNav').classList.remove('open')));$('#openRfqTop')?.addEventListener('click',()=>$('#rfq').scrollIntoView({behavior:'smooth'}));$('#toggleRange')?.addEventListener('click',()=>{const r=$('#fullRange');r.hidden=!r.hidden});$('#rfqProduct')?.addEventListener('change',syncPackOptions)}
async function submitRfq(e){e.preventDefault();const status=$('#rfqStatus'),btn=$('#sendRfq');const ids=['rfqProduct','rfqPack','rfqQuantity','rfqMarket','rfqCompany','rfqContact','rfqPhone'];if(ids.some(id=>!$('#'+id)?.value.trim())){status.textContent=t('rfq.required');status.className='err';return}const product=PRODUCTS.find(p=>p.id===$('#rfqProduct').value);const fd=new FormData();fd.append('_subject',`SANAAM RFQ | ${$('#rfqMarket').value} | ${$('#rfqCompany').value}`);fd.append('_template','table');fd.append('_captcha','false');fd.append('Product',product?`${product.name} · ${product.grade}`:$('#rfqProduct').value);fd.append('Pack Size',$('#rfqPack').value);fd.append('Estimated Quantity',$('#rfqQuantity').value);fd.append('Market / Country',$('#rfqMarket').value);fd.append('Destination Port',$('#rfqPort').value);fd.append('Company Name',$('#rfqCompany').value);fd.append('Contact Person',$('#rfqContact').value);fd.append('WhatsApp / Phone',$('#rfqPhone').value);fd.append('Notes',$('#rfqNotes').value);btn.disabled=true;status.textContent=t('rfq.sending');status.className='';try{const res=await fetch(CONFIG.formSubmitEndpoint,{method:'POST',headers:{Accept:'application/json'},body:fd});if(!res.ok)throw new Error('send');status.textContent=t('rfq.sent');status.className='ok';e.target.reset();populateRfqProducts(false)}catch{status.textContent=t('rfq.error');status.className='err'}finally{btn.disabled=false}}
function init(){bindNavigation();$('#rfqForm')?.addEventListener('submit',submitRfq);$$('.rfq-intro img,.footer-brand img').forEach(el=>el.remove());applyLanguage()}
init();
})();
