window.SANAAM_I18N = {
  so: {
    dir:'ltr',
    nav:{products:'Alaabta',applications:'Isticmaalka',origin:'Asalka Sucuudiga',packaging:'Baakadaha',distributors:'Qaybiyeyaasha',inquiry:'Dalab'},
    hero:{eyebrow:'Saliido Sucuudi ah oo loogu talagalay suuqyada dhoofinta',subtitle:'Saliidaha baabuurta, gaadiidka culus, qalabka iyo warshadaha',tagline:'Adkaysi. Kalsooni. Tayo.',body:'Saliido aasaasi ah oo Sucuudi ah, isku-darid, kontorool tayo iyo buuxin gudaha Boqortooyada, oo leh baakado ku habboon ganacsiga iyo dhoofinta.',explore:'Eeg Alaabta',build:'Samee Dalabkaaga'},
    origin:{kicker:'Asal Sucuudi',title:'Saliid aasaasi ah, wax-soo-saar gudaha ah, calaamad diyaar u ah dhoofinta',body:'SANAAM waxay isku xirtaa xoogga saliidaha aasaasiga ah ee Sucuudiga, isku-daridda iyo buuxinta gudaha dalka, baakadaha, iyo sahayda suuqyada Afrika.',step1:'Isha saliidda aasaasiga ah',step2:'Gudaha Sucuudiga',step3:'Calaamad & baakad',step4:'Qaybin & dhoofin'},
    featured:{kicker:'Alaabta muhiimka ah',title:'Noocyada muhiimka u ah baabuurta, gaadiidka culus iyo warshadaha',body:'Dooro grade-ka iyo cabbirka baakadka, kuna dar liiska dalabka qiimeynta.'},
    applications:{kicker:'Applications',title:'Laga bilaabo baabuurta magaalada ilaa qalabka culus',body:'Alaabta waxaa loo abaabulay baahiyaha baabuurta, gaadiidka culus, qalabka off-highway iyo warshadaha.',cards:[
      {code:'AUTOMOTIVE',title:'Baabuurta & ganacsiga fudud',text:'Matoorrada iyo nidaamyada gaadiidka maalinlaha ah.',items:['Baabuurta rakaabka','SUV iyo pickup','Taxi iyo vans','Basaska iyo gaadiidka ganacsiga fudud']},
      {code:'OFF-HIGHWAY HEAVY DUTY',title:'Qalabka culus & Off-Highway',text:'Shaqo culus oo ka jirta dhismaha, macdanta, dhagax-jebinta iyo qodista.',items:['Gaadiidka culus','Crushers iyo quarries','Excavators, loaders iyo bulldozers','Drilling & exploration rigs','Mining & construction equipment']},
      {code:'INDUSTRIAL',title:'Warshadaha',text:'Nidaamyada joogtada ah ee warshadaha iyo goobaha wax-soo-saarka.',items:['Warshadaha sibidhka','Gearboxes iyo compressors','Hydraulic systems','Production lines iyo generators','Dekedaha iyo bakhaarada']}
    ]},
    base:{kicker:'Saudi Base Oils',title:'Xoogga saliidaha aasaasiga ah ee Sucuudiga',body:'SANAAM waxay ku dhisan tahay saliido aasaasi ah oo Sucuudi ah oo ka yimaada Saudi Aramco, kadibna waxaa la sameeyaa isku-darid, xakamayn tayo iyo buuxin gudaha Boqortooyada si loogu adeego isticmaalka automotive, heavy-duty, off-highway iyo industrial.',source:'Isha saliidda aasaasiga ah',learn:'Arag Aramco Base Oils'},
    manufacturing:{kicker:'Saudi Manufacturing',title:'Isku-darid, shaybaar, kontorool tayo iyo buuxin gudaha Sucuudiga',body:'Habka wax-soo-saarku wuxuu ka bilaabmaa base oils iyo additives, kadib blending, baaritaanka shaybaarka iyo quality control, ugu dambayn filling iyo packaging.',process:['Base Oils & Additives','Blending','Laboratory & Quality','Filling & Packaging']},
    packaging:{kicker:'Packaging',title:'Cabbirro loogu talagalay shelf-ka, workshop-ka, fleet-ka iyo warshadaha',body:'1L, 4L, 5L, 20L iyo 200L waxay daboolayaan iibka tafaariiqda, adeegga workshop-ka, gaadiidka ganacsiga iyo sahayda warshadaha.'},
    families:{kicker:'Product Families',title:'Hal calaamad oo daboolaysa baahiyo badan',body:'Passenger car, heavy-duty diesel, gear, ATF, hydraulic iyo grease.'},
    familyNames:{pcmo:'Passenger Car Motor Oils',hdd:'Heavy-Duty Diesel Engine Oils',gear:'Gear Oils',atf:'Automatic Transmission Fluids',hydraulic:'Hydraulic Oils',grease:'Grease'},
    appLabels:{passenger:'Passenger Cars',offhighway:'Heavy-Duty & Off-Highway',gear:'Gearboxes & Axles',atf:'Automatic Transmissions',hydraulic:'Hydraulic Systems',industrial:'Industrial Equipment'},
    chain:{kicker:'Product Supply Chain',title:'Silsiladda alaabta hal eegis',steps:[['Saudi Base Oils','Base oil source'],['Saudi Manufacturing','Blending, laboratory & filling'],['SANAAM','Product identity & packaging'],['Export Markets','Distribution']]},
    distributors:{kicker:'For Distributors',title:'Alaab loogu talagalay qaybinta iyo dhoofinta',body:'Asal Sucuudi, grades badan, baakado kala duwan, automotive, heavy-duty, off-highway iyo industrial applications.',points:['Saudi Origin','Saudi Base Oils','Saudi Manufacturing','Multiple Viscosity Grades','1L to 200L Packaging','Passenger & Commercial Vehicles','Off-Highway Heavy Duty','Mining, Quarrying & Construction','Industrial Products','Technical Documentation'],cta:'Samee Dalabka Alaabta'},
    inquiry:{title:'Dalabka Alaabta',body:'Dooro alaabta, cabbirka iyo tirada. Dalabka waxaa lagu diri karaa email si toos ah.',empty:'Wax alaab ah laguma darin wali.',market:'Suuq / Wadan',company:'Magaca Shirkadda',contact:'Qofka lala xiriiro',phone:'WhatsApp / Telefoon',packaging:'Baakad',quantity:'Qiyaasta Tirada',notes:'Faahfaahin',copy:'Koobi',share:'La Wadaag',send:'Dir Dalabka',sending:'Waa la dirayaa...',sent:'Dalabka waa la diray.',sendError:'Diristu ma dhammaan. Koobi dalabka ama isku day mar kale.',required:'Buuxi suuqa, shirkadda, qofka xiriirka iyo telefoonka.',remove:'Ka saar',added:'Alaabta waa lagu daray',open:'Fur Dalabka'},
    card:{add:'Ku dar Dalabka',application:'Isticmaal',base:'Base Type',origin:'Origin'},fullRange:'Eeg dhammaan noocyada',footer:'SANAAM Lubricants · Saudi Lubricants'
  },
  en: {
    dir:'ltr',
    nav:{products:'Products',applications:'Applications',origin:'Saudi Origin',packaging:'Packaging',distributors:'Distributors',inquiry:'Inquiry'},
    hero:{eyebrow:'Saudi lubricants for export markets',subtitle:'Automotive, Heavy-Duty, Off-Highway & Industrial Lubricants',tagline:'Endurance. Trust. Quality.',body:'Saudi base oils, blending, quality control and filling in Saudi Arabia, supported by practical packaging for commercial and export distribution.',explore:'Explore Products',build:'Build Your Inquiry'},
    origin:{kicker:'Saudi Origin',title:'Saudi base oil strength transformed into finished lubricants',body:'SANAAM brings together Saudi base oils, local blending and filling, product packaging and export supply under one focused lubricant identity.',step1:'Base oil source',step2:'In Saudi Arabia',step3:'Brand & packaging',step4:'Distribution & export'},
    featured:{kicker:'Featured Products',title:'Core grades for automotive, heavy-duty and industrial markets',body:'Choose a grade and pack size, then add it to your product inquiry for pricing.'},
    applications:{kicker:'Applications',title:'From daily vehicles to demanding off-highway equipment',body:'The range is organized around automotive, heavy-duty, off-highway and industrial operating needs.',cards:[
      {code:'AUTOMOTIVE',title:'Automotive & Light Commercial',text:'Lubrication needs for daily transport and commercial mobility.',items:['Passenger cars','SUVs and pickups','Taxis and vans','Buses and light commercial vehicles']},
      {code:'OFF-HIGHWAY HEAVY DUTY',title:'Heavy-Duty & Off-Highway',text:'Demanding equipment across construction, mining, quarrying and drilling.',items:['Heavy trucks','Quarry crushers','Excavators, wheel loaders and bulldozers','Drilling & exploration rigs','Mining & construction equipment']},
      {code:'INDUSTRIAL',title:'Industrial',text:'Continuous-duty systems across plants and production environments.',items:['Cement plants','Gearboxes and compressors','Hydraulic systems','Production lines and generators','Ports and warehouses']}
    ]},
    base:{kicker:'Saudi Base Oils',title:'Built on Saudi base oil strength',body:'SANAAM is formulated around Saudi base oils sourced from Saudi Aramco, followed by blending, laboratory control and filling in Saudi Arabia for automotive, heavy-duty, off-highway and industrial applications.',source:'Base Oil Source',learn:'View Aramco Base Oils'},
    manufacturing:{kicker:'Saudi Manufacturing',title:'Blending, laboratory control and filling in Saudi Arabia',body:'The production flow starts with base oils and additives, moves through blending and laboratory quality control, then continues to filling and packaging.',process:['Base Oils & Additives','Blending','Laboratory & Quality','Filling & Packaging']},
    packaging:{kicker:'Packaging',title:'Formats for retail, workshops, fleets and industrial supply',body:'1L, 4L, 5L, 20L and 200L formats support retail shelves, workshops, commercial fleets and industrial supply.'},
    families:{kicker:'Product Families',title:'One brand across multiple lubricant needs',body:'Passenger car, heavy-duty diesel, gear, ATF, hydraulic and grease families.'},
    familyNames:{pcmo:'Passenger Car Motor Oils',hdd:'Heavy-Duty Diesel Engine Oils',gear:'Gear Oils',atf:'Automatic Transmission Fluids',hydraulic:'Hydraulic Oils',grease:'Grease'},
    appLabels:{passenger:'Passenger Cars',offhighway:'Heavy-Duty & Off-Highway',gear:'Gearboxes & Axles',atf:'Automatic Transmissions',hydraulic:'Hydraulic Systems',industrial:'Industrial Equipment'},
    chain:{kicker:'Product Supply Chain',title:'The product flow at a glance',steps:[['Saudi Base Oils','Base oil source'],['Saudi Manufacturing','Blending, laboratory & filling'],['SANAAM','Product identity & packaging'],['Export Markets','Distribution']]},
    distributors:{kicker:'For Distributors',title:'Built for practical export distribution',body:'Saudi origin, multiple viscosity grades, flexible pack sizes and coverage across automotive, heavy-duty, off-highway and industrial applications.',points:['Saudi Origin','Saudi Base Oils','Saudi Manufacturing','Multiple Viscosity Grades','1L to 200L Packaging','Passenger & Commercial Vehicles','Off-Highway Heavy Duty','Mining, Quarrying & Construction','Industrial Products','Technical Documentation'],cta:'Build Your Product Inquiry'},
    inquiry:{title:'Your Product Inquiry',body:'Choose products, packaging and quantity, then send the inquiry directly by email.',empty:'No products added yet.',market:'Market / Country',company:'Company Name',contact:'Contact Person',phone:'WhatsApp / Phone',packaging:'Packaging',quantity:'Estimated Quantity',notes:'Notes',copy:'Copy',share:'Share',send:'Send Inquiry',sending:'Sending...',sent:'Inquiry sent successfully.',sendError:'The inquiry was not sent. Copy it or try again.',required:'Complete market, company, contact person and phone.',remove:'Remove',added:'Product added',open:'Open Inquiry'},
    card:{add:'Add to Inquiry',application:'Application',base:'Base Type',origin:'Origin'},fullRange:'View Full Range',footer:'SANAAM Lubricants · Saudi Lubricants'
  },
  ar: {
    dir:'rtl',
    nav:{products:'المنتجات',applications:'الاستخدامات',origin:'المنشأ السعودي',packaging:'العبوات',distributors:'الموزعون',inquiry:'الطلب'},
    hero:{eyebrow:'زيوت سعودية لأسواق التصدير',subtitle:'زيوت للسيارات والشاحنات والمعدات والصناعة',tagline:'تحمل. ثقة. جودة.',body:'زيوت أساس سعودية، خلط وضبط جودة وتعبئة داخل المملكة، مع عبوات عملية للتوزيع التجاري وأسواق التصدير.',explore:'استكشف المنتجات',build:'جهز طلبك'},
    origin:{kicker:'المنشأ السعودي',title:'قوة زيوت الأساس السعودية تتحول إلى زيوت تشحيم جاهزة للسوق',body:'تجمع سنام بين زيوت الأساس السعودية، والخلط والتعبئة داخل المملكة، وهوية المنتج والعبوات، ثم التوريد لأسواق التصدير.',step1:'مصدر زيت الأساس',step2:'داخل المملكة',step3:'العلامة والعبوات',step4:'التوزيع والتصدير'},
    featured:{kicker:'منتجات بارزة',title:'درجات أساسية للسيارات والاستخدامات الشاقة والصناعة',body:'اختر درجة اللزوجة والعبوة، ثم أضف المنتج إلى طلب التسعير.'},
    applications:{kicker:'الاستخدامات',title:'من سيارات الاستخدام اليومي إلى المعدات الثقيلة خارج الطرق',body:'يغطي نطاق المنتجات احتياجات السيارات، الشاحنات، المعدات الثقيلة خارج الطرق، والأنظمة الصناعية.',cards:[
      {code:'AUTOMOTIVE',title:'السيارات والمركبات التجارية الخفيفة',text:'زيوت للمحركات وأنظمة الحركة في الاستخدام اليومي والتجاري.',items:['سيارات الركاب','سيارات SUV والبيك أب','سيارات الأجرة والفانات','الحافلات والمركبات التجارية الخفيفة']},
      {code:'OFF-HIGHWAY HEAVY DUTY',title:'الاستخدامات الشاقة والمعدات خارج الطرق',text:'معدات تعمل تحت الأحمال العالية في الإنشاءات والتعدين والمحاجر والتنقيب.',items:['الشاحنات الثقيلة','كسارات المحاجر','الحفارات واللوادر والجرافات','معدات الحفر والتنقيب','معدات التعدين والإنشاءات']},
      {code:'INDUSTRIAL',title:'الاستخدامات الصناعية',text:'أنظمة تشغيل مستمر داخل المصانع والمنشآت الإنتاجية.',items:['مصانع الأسمنت','علب التروس والضواغط','الأنظمة الهيدروليكية','خطوط الإنتاج والمولدات','الموانئ والمستودعات']}
    ]},
    base:{kicker:'زيوت الأساس السعودية',title:'قوة زيوت الأساس السعودية',body:'تعتمد زيوت سنام على زيوت أساس سعودية من أرامكو السعودية، ثم الخلط والاختبارات المخبرية وضبط الجودة والتعبئة داخل المملكة لخدمة السيارات والاستخدامات الشاقة والمعدات خارج الطرق والتطبيقات الصناعية.',source:'مصدر زيت الأساس',learn:'معلومات Aramco Base Oils'},
    manufacturing:{kicker:'التصنيع السعودي',title:'الخلط والمختبر وضبط الجودة والتعبئة داخل المملكة',body:'تبدأ رحلة الإنتاج بزيوت الأساس والإضافات، ثم الخلط، والفحص المخبري وضبط الجودة، وبعدها التعبئة والتغليف.',process:['زيوت الأساس والإضافات','الخلط','المختبر وضبط الجودة','التعبئة والتغليف']},
    packaging:{kicker:'العبوات',title:'أحجام للرف والورشة والأسطول والتوريد الصناعي',body:'أحجام 1L و4L و5L و20L و200L تخدم التجزئة، الورش، الأساطيل التجارية، والمصانع والمشروعات.'},
    families:{kicker:'عائلات المنتجات',title:'علامة واحدة لاحتياجات تشحيم متعددة',body:'زيوت سيارات، ديزل ثقيل، جير، ناقل حركة أوتوماتيكي، هيدروليك وشحوم.'},
    familyNames:{pcmo:'زيوت محركات سيارات الركاب',hdd:'زيوت محركات الديزل للخدمة الشاقة',gear:'زيوت التروس والجير',atf:'سوائل ناقل الحركة الأوتوماتيكي',hydraulic:'زيوت الهيدروليك',grease:'الشحوم'},
    appLabels:{passenger:'سيارات الركاب',offhighway:'Heavy-Duty & Off-Highway',gear:'علب التروس والمحاور',atf:'ناقل الحركة الأوتوماتيكي',hydraulic:'الأنظمة الهيدروليكية',industrial:'المعدات الصناعية'},
    chain:{kicker:'سلسلة المنتج',title:'رحلة المنتج في نظرة واحدة',steps:[['زيوت أساس سعودية','مصدر زيت الأساس'],['التصنيع السعودي','الخلط والمختبر والتعبئة'],['SANAAM','هوية المنتج والعبوات'],['أسواق التصدير','التوزيع']]},
    distributors:{kicker:'للموزعين',title:'منظومة عملية للتوزيع والتصدير',body:'منشأ سعودي، درجات لزوجة متعددة، عبوات من 1L إلى 200L، ونطاق يخدم السيارات والاستخدامات الشاقة والمعدات خارج الطرق والصناعة.',points:['منشأ سعودي','زيوت أساس سعودية','تصنيع سعودي','درجات لزوجة متعددة','عبوات من 1L إلى 200L','سيارات ومركبات تجارية','Off-Highway Heavy Duty','التعدين والمحاجر والإنشاءات','منتجات صناعية','وثائق فنية'],cta:'جهز طلب المنتجات'},
    inquiry:{title:'طلب المنتجات',body:'اختر المنتجات والعبوات والكميات، ثم أرسل الطلب ليصل مباشرة بالبريد الإلكتروني.',empty:'لم تضف منتجات بعد.',market:'السوق / الدولة',company:'اسم الشركة',contact:'اسم الشخص',phone:'واتساب / هاتف',packaging:'العبوة',quantity:'الكمية التقريبية',notes:'ملاحظات',copy:'نسخ',share:'مشاركة',send:'إرسال الطلب',sending:'جار الإرسال...',sent:'تم إرسال الطلب.',sendError:'تعذر إرسال الطلب. انسخ الطلب أو حاول مرة أخرى.',required:'أكمل السوق واسم الشركة واسم الشخص ورقم التواصل.',remove:'حذف',added:'تمت إضافة المنتج',open:'فتح الطلب'},
    card:{add:'أضف إلى الطلب',application:'الاستخدام',base:'نوع الأساس',origin:'المنشأ'},fullRange:'عرض كامل المنتجات',footer:'SANAAM Lubricants · Saudi Lubricants'
  }
};
